export const CDN_PATH = 'https://3gimg.qq.com/lightmap/xcx/demoCenter/images';
export const COS_PATH = 'https://mapapi.qq.com/web/miniprogram/demoCenter/images';
export const PLUGIN_KEY = 'Q3TBZ-ZPECZ-6VGX5-T3YFE-R2N3V-G5BU7';
export const MOYUAN_KEY = '';
export const BAIQIAN_KEY = '';
export const YULU_KEY = '';
export const DIFUNI_KEY = '';
export const INDOOR_KEY = '';
export const REFERER = 'Dreamy Tour';
export const WEBSERVICE_APPID = 'wx6c0d5ae365e9b82d';
export const CUSTOM_KEY = ''; // 个性化地图key
export const WS_HOST = 'https://apis.map.qq.com'
export const SMART_SOLUTION_KEY = ''; //出行解决方案key
export const NEARBY_CAR_KEY = '';
export const NEARBY_CAR_SK = ''; //出行解决方案sk